package selenium.automation.psmg.model;

public enum Context {
	HITSNOINITIAL, RESPONSEGET, RESPONSEPOST, RESPONSESOAPKEYVALUE, RESPONSESOAPVALUE,
	PDMGENERICPARENTGUID, PDMGUIDMMGNODE, PDMGUIDGENERICPARTNODE, GENERICPARTGUIDMATERIALNODE, PRODUCTVALUE
}
